### ISSUE TITLE
Add a setting to select the amount of notifications that the extension shows

### ISSUE THREAD

**Issue by AngelEzquerra** [nim-lang/vscode-nim#34]
At the moment the extension is a bit "chatty", i.e. it shows a lot notifications (e.g. to indicate that it started parsing a file, that there was an error and it restarted the LSP, etc). It would be nice to have a way to select either the level of notifications or alternatively to enable of disable certain notifications.

**Comment by jmgomez** [comment]
Implemented via https://github.com/nim-lang/vscode-nim/commit/2cd76db84549970ac73dae0fa1ccd373a8172085
Notice it does require the latest version of the langserver as the notifications come from it.
