### ISSUE TITLE
Binary named 'nim' not found in PATH environment variable, even when nim exists in PATH

### ISSUE THREAD

**Issue by MKuranowski** [nim-lang/vscode-nim#35]
This extension suffers from the same problem as https://github.com/saem/vscode-nim/issues/136.

I have nim and nimlangserver downloaded and placed somewhere in `~/Documents`. Symlinks to those executables are then placed in `~/.local/share/bin`, which **exists in PATH**.

`/home/mikolaj/.local/share/bin/` is added to the path in `$HOME/.zshrc`; which would *normally* not be visible to programs launched from a DE. **However**, [VS Code sources `.zshrc`](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails) so this should not be a problem. Other extensions happily work which this configuration - my .zshrc also sets GOPATH, which is automatically picked up by the official Go extension.

Some part of this extension must incorrectly inherit the environment from VS Code.

**Comment by RokkuCode** [comment]
vscode tries to source the zshrc, but you shoul have a look at vscode.process in developer tools, to verify that the PATH var is correctly loaded. if not then there is a problem with vscode. do you have the same problem if you start code from a terminal with `code .`?
