### ISSUE TITLE
nim-lang.org extension v0.9.0 fails activation

### ISSUE THREAD

**Issue by aboisvert** [nim-lang/vscode-nim#43]
nim-lang.org v0.9.0 fails activation

Under the "Runtime Status" tab of the extension I see the following errors:

```
Uncaught Errors (9)
Pending response rejected since connection got disposed
Client is not running and can't be stopped. It's current state is: starting
Client is not running and can't be stopped. It's current state is: startFailed
write EPIPE
Client is not running and can't be stopped. It's current state is: startFailed
Cannot call write after a stream was destroyed
Client is not running and can't be stopped. It's current state is: starting
write EPIPE
Client is not running and can't be stopped. It's current state is: starting
```

My system information:

```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

% uname -a
Linux smudge 6.5.0-17-generic #17-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 11 14:01:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

% nim -v 
Nim Compiler Version 2.0.2 [Linux: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c4c44d10df8a14204a75c34e499def200589cb7c
active boot switches: -d:release

% nimble -v
nimble v0.14.2 compiled at 2023-12-15 01:05:41

% nimble install nimlangserver
Downloading https://github.com/nim-lang/langserver using git
 Installing nimlangserver@1.2.0
  Warning:  A package "nimlangserver@1.2.0" with checksum "95de85fae4485dcd850ada31e200d15671a00c4a" already exists the the cache.
```

**Comment by aboisvert** [comment]
How can I get more debug info to help diagnose this?

**Comment by aboisvert** [comment]
Note:  the `nimsaem` extension works just fine on the same computer  (when installed separately;  I did not have both extensions installed at the same time)

**Comment by nickysn** [comment]
> How can I get more debug info to help diagnose this?

In the "Output" window (Ctrl+K Ctrl+H), select from the drop down in the upper right corner "Nim" and "Nim Language Server". If there is no "Nim Language Server" tab, that could mean that nimlangserver is not found in the PATH.

**Comment by aboisvert** [comment]
Turns out this was due to `nimlangserver` missing a dependency on my system:

```sh
%> nimlangserver 
could not load: libpcre.so(.3|.1|)
(compile with -d:nimDebugDlOpen for more information)
```

This sounds like an issue for `nimlangserver` ... it should probably check that `libpcre` is installed on the system during installation.

**Comment by aboisvert** [comment]
Closing since the issue lies with `nimlangserver`.

**Comment by aboisvert** [comment]
Reported `nimlangserver` enhancement as https://github.com/nim-lang/langserver/issues/187
