### ISSUE TITLE
Plugin stops detecting compiler flags after changing source files

### ISSUE THREAD

**Issue by Spirarel** [nim-lang/vscode-nim#54]
Here's a small example
```{nim}
include prelude

type GraphNode[T] = ref object
  value: T
  neighbors: seq[GraphNode[T]]

iterator items[T](graphNode: GraphNode[T]): GraphNode[T] =
  var
    s = @[graphNode]
    seen = initHashSet[GraphNode[T]]()
    curr: GraphNode[T]
  while s.len > 0:
    curr = s.pop
    yield curr
    seen.incl curr
    for e in curr.neighbors:
      if e notin seen:
        s.add e

let nodes = GraphNode[int](value: 1, neighbors: @[GraphNode[int](value: 2, neighbors: @[])])

for i in nodes:
  echo i.value
```
compile with `-d:nimPreviewHashRef`

Restarting vscode and building on save. The code compiles and runs, there are no problems highlighted:
<img width="1017" alt="Screenshot 2024-03-22 at 8 56 27 AM" src="https://github.com/nim-lang/vscode-nim/assets/10119394/ac5e21f1-83bd-4aff-aa23-5075c418210f">

Add a few newlines to the end and build & run again. The code compiles and runs fine, but the plugin shows problems:

<img width="967" alt="Screenshot 2024-03-22 at 8 57 01 AM" src="https://github.com/nim-lang/vscode-nim/assets/10119394/4b714ec7-4f49-4823-97a0-8243fcc06ad2">

This greatly limits the plugin's usefulness.

---
extension: v0.9.0
vscode: 1.87.2
nim: 2.0.2

**Comment by jmgomez** [comment]
Sounds like the issue is that `nimsuggest` doesnt know about `-d:nimPreviewHashRef`. 
Create a `config.nims` and `--d:nimPreviewHashRef` to it
Reopen if it doenst fix it.

**Comment by Spirarel** [comment]
Hmm I added this file with the entry to the directory; it's getting picked up by the build task, but the plugin is still showing issues. Does the extension require extra configuration?

**Comment by jmgomez** [comment]
No, it doesnt require extra configuration. Can you share your file structure? `config.nims` should be near the entry point

**Comment by Spirarel** [comment]
Essentially flat,
<img width="236" alt="Screenshot 2024-03-31 at 6 11 26 PM" src="https://github.com/nim-lang/vscode-nim/assets/10119394/230b71f5-8b3e-4b4a-9fe5-81a40f39e29b">

<img width="278" alt="Screenshot 2024-03-31 at 6 12 05 PM" src="https://github.com/nim-lang/vscode-nim/assets/10119394/2d0a7aea-ffe4-47aa-afe5-25b17bd6ae18">

**Comment by jmgomez** [comment]
I mean the actual files with a minimal repro
