### ISSUE TITLE
Nim VS code attach to process

### ISSUE THREAD

**Issue by ironpython2001** [nim-lang/vscode-nim#60]
I am using vscode as an ide for NIM. How to attach to running process in vscode for NIM.

Here is my vscode configuration. Is this correct ..? I am not able to attach to running process
``

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "attach",
            "name": "Attach",
             "pid": "${command:pickProcess}", // use ${command:pickProcess} to pick other users' processes
             "program": "${workspaceFolder}/bin/${fileBasenameNoExtension}.exe",
             "stopOnEntry" : true,
        }
    ]
}
``

**Comment by jmgomez** [comment]
Like this: 
```json
    {
      "type": "lldb",
      "request": "attach",
      "name": "Attach test",
      "program": "${workspaceFolder}/pathToYourExec",
  },
  ````
  
  Make sure you compiled it with `debugger:native`
