### ISSUE TITLE
Autocomplete is wrong

### ISSUE THREAD

**Issue by al6x** [nim-lang/vscode-nim#62]
Autocomplete suggest `bottom` enum value, which is wrong, the function argument has different type.

<img width="502" alt="Screen Shot 2024-05-24 at 8 34 51 pm" src="https://github.com/nim-lang/vscode-nim/assets/94196/6cebb73e-c0f2-4c8b-9c53-2fb5686e018c">

The code

```
type
  Align = enum top, right, bottom, left
  Direction = enum up, right, down, left

proc move(d: Direction) =
  echo d

move(b)
```

**Comment by jmgomez** [comment]
The `abc` marker is not coming from the extension.

**Comment by al6x** [comment]
@jmgomez can you please explain? what is the problem and how to fix it?

**Comment by al6x** [comment]
I figured it out, abc suggestion cames from "word suggest" option. I think nim extension should disable that option, as all other languages do. It's confusing. 

The issue should be reopened.

**Comment by jmgomez** [comment]
It is the case already, your problem is likely another:
![image](https://github.com/nim-lang/vscode-nim/assets/1496571/eac0a88c-e1f5-42a2-9e02-893d7c3863f6)

**Comment by al6x** [comment]
I fixed it. Now, it's still broken. It suggest all sorts of nonsense, except of what's needed the `up` should be in the top of the list. 

<img width="523" alt="Screen Shot 2024-06-03 at 7 16 59 pm" src="https://github.com/nim-lang/vscode-nim/assets/94196/9fb467ae-69d8-4e73-9673-b617d6a3f0ab">

**Comment by jmgomez** [comment]
> It's still broken
I cant see the `Word Suggest` there. As for the ordering issue/items not appearing, the list is coming from `nimsuggest` not from the extension.
