### ISSUE TITLE
`Server failed with Nimsuggest process crashed.`

### ISSUE THREAD

**Issue by dysrakescence** [nim-lang/vscode-nim#79]
While setting up the LSP server for Nim, I ran into a problem. It seems like Nimsuggest crashes without a reason. I tried downloading nimlangserver from nimble but it didn't solve anything. I tried uninstalling Nim and reinstalling, constantly restarting both VSCode and the LSP extension, but nothing changes. Here's my LSP info tab: 
![image](https://github.com/user-attachments/assets/ddee6b39-93de-4edb-8743-c34466533660)
As of currently, this extension is only capable of highlighting text in my Nim files, which wasn't as helpful as I had hoped, unless the LSP extension is only meant for adding color to text? Does anyone else have this issue?

**Comment by jmgomez** [comment]
Do this also happen to you in an empty nim file? Also make sure you update your `nim` to the latest version

**Comment by dysrakescence** [comment]
It seems like updating my Nim to the latest version fixed my problem! I used the Arch Linux Extra repository and it appears that the maintainer hasn't been updating it since May 14th, so the Nim version was stuck on 2.0.4. Thanks for the help!
